### ISSUE TITLE
[BUG] Excluded directory is checked.

### ISSUE THREAD

**Issue by 1kastner** [s-weigand/flake8-nb#254]
**Describe the bug**
Directories that I want to exclude and that were previously excluded are not scanned by flake8_nb.

**To Reproduce**

1. Create a `.flake8_nb` file with the following content:

```
exclude =
    *.git*
    *venv*
    *.ipynb_checkpoints*
    *.virtual_documents*
    *build*
    *.py
```
2. Run `flake8_nb` from the CI
3. Observe how it enters the directory `.virtual_documents` where it should not end up!

**Expected behavior**
The excluded directories, such as  `.virtual_documents` , should not be checked.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: flake8_nb-0.5.1

**Additional context**
This was working with flake8-nb-0.4.0

**Comment by 1kastner** [comment]
I additionally checked and yes, downgrading to 0.4.0 made my config work again.

**Comment by 1kastner** [comment]
Btw, I also came up with that config by try-and-error, my flake8 config does not incude those asterisks.

**Comment by s-weigand** [comment]
When hacking the flake8 config  module I forgot to also replace [the hardcoded `.flake8`](https://github.com/PyCQA/flake8/blob/e249dc47dfd314c34bbd0946c3fad970a8b15d6c/src/flake8/options/config.py#L33) 🤦‍♀️

I will add a fix+test and make a new release

**Comment by 1kastner** [comment]
Cool, thanks!

**Comment by 1kastner** [comment]
@s-weigand do you see the option to add some automated test for this to avoid future regression? That would be awesome! Maybe inside https://github.com/s-weigand/flake8-nb/tree/main/tests/data there could be a subfolder that is used as a root folder to run flake8_nb and it is checked whether `.flake8_nb` has been read in and used?

**Comment by s-weigand** [comment]
@1kastner I added a [test for that](https://github.com/s-weigand/flake8-nb/blob/3f74f3f4f5b63675dbcaef256f1d621e5000c1f3/tests/test__main__.py#L81-L108) in #255 when fixing the issue 😊
Due to how the config section discovery works you might need to add `[flake8_nb]` on the top of your `.flake8_nb` not sure if that was needed before 🤔
I use `setup.cfg`, `pyproject.toml` and `tox.ini` for all my configs if the tool allows it

Anyway `0.5.2` is on PyPi and should fix the bug 🎉

**Comment by 1kastner** [comment]
That's great, thanks a lot!
